# Generated by Django 3.0.1 on 2022-04-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('yearExp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ageLimit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('gender', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='XL', max_length=5)),
                ('brand', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('inPrice', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('outPrice', models.FloatField()),
                ('state', models.CharField(max_length=255)),
                ('storage_quantity', models.IntegerField(default=0)),
                ('available_status', models.BooleanField(default=False)),
                ('imageItem', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenSize', models.FloatField(default=0)),
                ('screenResolution', models.CharField(default='Full HD', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('inPrice', models.FloatField(default=0)),
                ('brandID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Brand')),
                ('electronicID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Electronic')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('screenSize', models.FloatField(default=0)),
                ('ram', models.IntegerField(default=4)),
                ('memory', models.IntegerField(default=64)),
                ('color', models.CharField(max_length=255)),
                ('inPrice', models.FloatField(default=0)),
                ('brandID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Brand')),
                ('electronicID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Electronic')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardWareSize', models.IntegerField(default=128)),
                ('hardWareType', models.CharField(default='SSD', max_length=3)),
                ('screenSize', models.FloatField(default=0)),
                ('screenResolution', models.CharField(default='Full HD', max_length=10)),
                ('cpu', models.CharField(max_length=255)),
                ('ram', models.IntegerField(default=8)),
                ('name', models.CharField(max_length=255)),
                ('inPrice', models.FloatField(default=0)),
                ('brandID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Brand')),
                ('electronicID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Electronic')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('star_rate', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Item')),
            ],
        ),
        migrations.AddField(
            model_name='electronic',
            name='itemID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Item'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('inPrice', models.FloatField(default=0)),
                ('publishYear', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('category', models.IntegerField()),
                ('CategoryBookID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.CategoryBook')),
                ('authorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Author')),
                ('itemID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Item')),
                ('publisherID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Publisher')),
            ],
        ),
    ]
