# Generated by Django 3.0.1 on 2022-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='categoryclothes',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categoryclothes',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('M', 'M'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL')], max_length=5),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='Category',
            field=models.CharField(choices=[('MB', 'MobliePhone'), ('TV', 'Television'), ('Clothes', 'Clothes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hardWareType',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SDD', 'SDD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screenResolution',
            field=models.CharField(choices=[('HD', 'HD'), ('HD_PLUS', 'HD+'), ('FHD', 'FullHD'), ('QHD', '2K'), ('UHD', '4K')], max_length=10),
        ),
        migrations.AlterField(
            model_name='television',
            name='screenResolution',
            field=models.CharField(choices=[('HD', 'HD'), ('HD_PLUS', 'HD+'), ('FHD', 'FullHD'), ('QHD', '2K'), ('UHD', '4K')], max_length=10),
        ),
    ]
