# Generated by Django 3.0.1 on 2022-04-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220412_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imageItem',
            field=models.ImageField(blank=True, null=True, upload_to='product_imgs/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('BOOK', 'BOOK'), ('ELECTRONIC', 'ELECTRONIC'), ('CLOTHES', 'CLOTHES')], default='BOOK', max_length=255),
        ),
    ]
