# Generated by Django 3.0.1 on 2022-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220420_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': '1.(BOOK)_Author'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '4.(BOOK)_Book'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '5.(ELECTRONIC)_Brand'},
        ),
        migrations.AlterModelOptions(
            name='categorybook',
            options={'verbose_name_plural': '3.(BOOK)_Category'},
        ),
        migrations.AlterModelOptions(
            name='categoryclothes',
            options={'verbose_name_plural': '9(3).(CLOTHES)_Category'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': '9(2).(CLOTHES)_Clothes'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '9(6).(ITEM)_Comment'},
        ),
        migrations.AlterModelOptions(
            name='electronic',
            options={'verbose_name_plural': '9(1).(ELECTRONIC)_Electronic'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': '9(5).(ITEM)_FeedBack'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': '9(4).(ITEM)_Item'},
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name_plural': '8.(ELECTRONIC)_Laptop'},
        ),
        migrations.AlterModelOptions(
            name='mobilephone',
            options={'verbose_name_plural': '6.(ELECTRONIC)_MobilePhone'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name_plural': '2.(BOOK)_Publisher'},
        ),
        migrations.AlterModelOptions(
            name='television',
            options={'verbose_name_plural': '7.(ELECTRONIC)_Television'},
        ),
        migrations.AddField(
            model_name='brand',
            name='imageBrand',
            field=models.ImageField(blank=True, null=True, upload_to='brands_imgs/'),
        ),
    ]
