# Generated by Django 3.0.1 on 2022-04-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220420_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_Featured',
            field=models.BooleanField(default=False),
        ),
    ]
