# Generated by Django 3.0.1 on 2022-05-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220420_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryitem',
            options={'verbose_name_plural': '9(7).(ITEM)_CategoryItem'},
        ),
    ]
