# Generated by Django 3.0.1 on 2022-04-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zipcode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('shippingStatus', models.BooleanField(default=False)),
                ('paymentMethod', models.CharField(max_length=200, null=True)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('completedStatus', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportationType', models.CharField(max_length=200, null=True)),
                ('shipFee', models.FloatField(default=0)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(default=None)),
                ('orderID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderCart.Order')),
                ('shipmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderCart.AddressShip')),
            ],
        ),
    ]
