# Generated by Django 3.0.1 on 2022-04-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('orderCart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='itemID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderCart.Order'),
        ),
    ]
