# Generated by Django 3.0.1 on 2022-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderCart', '0002_auto_20220412_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingStatus',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='transportationType',
            field=models.CharField(choices=[('GHTK', 'GIAO HANG TIET KIEM'), ('J&T', 'J&T'), ('VNPT', 'VNPT')], max_length=50, null=True),
        ),
    ]
